### ISSUE TITLE
Unable to Reinstall ShipperHQ on Magento 2.3.7 after Uninstall

### ISSUE THREAD

**Issue by nickpiro** [shipperhq/module-shipper#123]
Hello,

We accidentally upgraded your module to the latest version on our production website and it caused the site to break. We attempted to roll back that module to the working version, but this was not working. We then uninstalled the module (via composer) and the module deleted all of the attribute tables, but left the setup_module intact as well as random tables throughout the database. I deleted the setup_module table entries for ShipperHQ, but when I re-installed the module, the module still did not create the necessary tables for it to work. 

We installed version 20.47.6

Is there anything specific that we need to do to get these tables to be recreated? I assumed removing the setup_module entries would have done the trick.

Thank you!

**Comment by nickpiro** [comment]
Is ShipperHQ no longer in business? I've been calling for weeks, left VMs, emailed support, created this Git ticket as the last resort and still no response. Our company relies heavily on dimensional shipping and we're completely SOL at the moment. Anyone know of another dimensional shipping module? Thanks!

**Comment by wsajosh** [comment]
Hey @nickpiro 

Apologies for the lack of communication. We're reviewing that aspect internally as to what went wrong - we're certainly still here and available on phone, chat and email. My colleague has replied to your email already but I'll post the solution here too in case anyone else is following the issue. 

The issue is that Magento is not removing the entries from patch_list when the module is uninstalled - they will need to be removed manually in addition to the entries in setup_module. Once you've manually deleted all entries related to ShipperHQ then you will need to run php bin/magento setup:upgrade and refresh the caches and indexes.

I hope this helps. I can see that you've sent a reply to the open ticket that is with Peter, he should send you a reply today once he's online
