### ISSUE TITLE
error "cardId is a required field" when select shipping address of customer

### ISSUE THREAD

**Issue by htmyheart** [shipperhq/module-shipper#27]
Magento 2.1.7
When customer login and checkout, at step 1 (shipping), customer select his shipping address, have a request to server and it return error: cardId is a required field. Could you please check:

![image](https://user-images.githubusercontent.com/4941829/28061116-9222fa26-6653-11e7-9fad-30183ec94354.png)

**Comment by wsagen** [comment]
Thanks for raising the issue. I've reviewed the error you reported as well as our code. I believe this is an issue with Magento 2 rather than ShipperHQ. It's been raised as an open issue on Magento here
https://github.com/magento/magento2/issues/1443

If you have specific steps to reproduce I suggest you add them to this open issue.

**Comment by htmyheart** [comment]
Thank you so much

**Comment by CRYX2** [comment]
Same problem, no workaround yet?

**Comment by wsagen** [comment]
@CRYX2 see my comment above when I closed the issue. It's a problem with Magento 2
