### ISSUE TITLE
main.CRITICAL: Item (Magento\Framework\View\Element\UiComponent\DataProvider\Document) with the same ID "637" already exists

### ISSUE THREAD

**Issue by nickpiro** [shipperhq/module-shipper#63]
We have been receiving this error ever since installing ShipperHQ. We're in the process of removing the tables (for a second time now) to hopefully resolve this issue. Does anyone know what could be causing this? The module was enabled via module:enable but wasn't enabled in the backend. The columns were still created on the order grid and visible even though it was disabled.

I've now disabled the module but the issue is still persisting so I'm going to go through and remove all tables again.

Seems we'll never be able to use this module at this point. Keeps destroying our site!

Magento version 2.2.5

**Comment by TravisBernard** [comment]
Hi @nickpiro happy to help you out.

So if I understand correctly, you've disabled module-shipper but you're still seeing the custom columns (delivery date, dispatch date, etc) on the order grid?  Or have I misunderstood?

This sounds like a cache/DI issue. Can you please share the following with me?

- Is this a live or development environment?
- What's the output of `php bin/magento deploy:mode:show`
- Since you've disabled the module have you cleared your cache and your `generated/` directory?
- If deploy mode is production then have you run `php bin/magento setup:di:compile` since you've disabled the module?
