### ISSUE TITLE
Class shipperhq_shipper/carrier_shipper does not exist issue after installing 

### ISSUE THREAD

**Issue by hemendraajmera** [shipperhq/module-shipper#74]
I have installed the extension using composer and login in admin and navigate to sales> shipping method.
it through error on page 
Class shipperhq_shipper/carrier_shipper does not exist 
can you please help to resolve the issue

Magento ver. 2.3.3

**Comment by wsajason** [comment]
Hi,

Ensure that the instance has been cleaned up with the following steps:

Flush the cache
Remove generated file content by deleting contents of:
```
var/view_preprocessed
pub/static/frontend/
pub/static/adminhtml/
pub/static/_requirejs/
generation (or var/generation )
var/cache
var/page_cache
```
If you are in default or production mode, you will need to recompile your code bin/magento `setup:di:compile`

For reference the issue requests and support email requests are sent through to the same support team.

**Comment by TravisBernard** [comment]
Hi Hemendra.  It looks like your store data was migrated from Magento 1 to Magento 2 is that correct?  Because of platform difference not all of the SHQ data can move over without some changes.  We have a doc about that here: https://docs.shipperhq.com/migrating-shipperhq-extension-magento1-magento2/.  If you will please
​
​Uninstall ShipperHQ
​Run through steps 2-4 of the document I've linked
​Reinstall ShipperHQ following the Clean Install section of this doc: https://docs.shipperhq.com/installing-magento-2-shipperhq-extension/#Clean_Install
Especially be careful to make sure you don't skip the setup:update and cache:flush steps.

​That should solve your problem.  I'm closing this issue since we already have a support ticket open for you in our help system.  Feel free to reply to that or email support at shipperhq.com if you have any further questions.
